name: lint-chimedb.data_index
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:

  lint-code:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Install black
      run: pip install black

    - name: Check code with black
      run: black --check .
