name: test-chimedb.data_index
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  run-tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip dependencies
      run: |
        pip install .
        pip install .[test]

    - name: Run tests
      run: pytest -sv test/
